'use client'

import { useEffect, useState, Suspense } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import {
  CheckCircle2, XCircle, ArrowRight, RefreshCw, Brain, BarChart2,
  TrendingUp, AlertTriangle, Zap, ChevronRight, Loader2,
} from 'lucide-react'
import { cn, getRiskColor, getRiskBgColor, getRiskLabel, getScoreColor } from '@/lib/utils'
import type { AssessmentResponse, RiskBand } from '@/lib/types'

// ─── Score Ring SVG ──────────────────────────────────────────
function ScoreRing({ score, band }: { score: number; band: RiskBand }) {
  const r = 54
  const circ = 2 * Math.PI * r
  const filled = ((100 - score) / 100) * circ
  const color = getScoreColor(score)

  return (
    <div className="relative w-[160px] h-[160px] mx-auto">
      <svg viewBox="0 0 120 120" className="w-full h-full -rotate-90">
        {/* Track */}
        <circle cx="60" cy="60" r={r} fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="8" />
        {/* Progress */}
        <circle
          cx="60" cy="60" r={r}
          fill="none"
          stroke={color}
          strokeWidth="8"
          strokeLinecap="round"
          strokeDasharray={circ}
          strokeDashoffset={filled}
          style={{ transition: 'stroke-dashoffset 1.2s ease-out' }}
        />
      </svg>
      {/* Center text */}
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-4xl font-bold text-white tabular-nums">{score}</span>
        <span className="text-xs text-white/40">/ 100</span>
      </div>
    </div>
  )
}

// ─── Main Dashboard ──────────────────────────────────────────
function DashboardContent() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const id = searchParams.get('id')

  const [result, setResult] = useState<AssessmentResponse | null>(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    const stored = sessionStorage.getItem('scorify_result')
    if (stored) {
      try {
        const data = JSON.parse(stored)
        setResult(data)
      } catch {
        router.replace('/assessment')
      }
    } else {
      router.replace('/assessment')
    }
    setIsLoading(false)
  }, [router, id])

  if (isLoading) {
    return (
      <div className="min-h-screen pt-16 flex items-center justify-center">
        <div className="text-center">
          <Loader2 size={32} className="animate-spin text-blue-400 mx-auto mb-4" />
          <p className="text-white/50 text-sm">Loading your credit intelligence...</p>
        </div>
      </div>
    )
  }

  if (!result) return null

  const { score, risk_band, confidence, key_positive_factors, key_negative_factors } = result
  const riskColor = getRiskColor(risk_band)
  const riskBg = getRiskBgColor(risk_band)
  const riskLabel = getRiskLabel(risk_band)

  return (
    <div className="min-h-screen pt-16">
      <div className="max-w-6xl mx-auto px-6 py-12">

        {/* Header */}
        <div className="flex items-start justify-between flex-wrap gap-4 mb-10">
          <div>
            <p className="section-label mb-2">Credit Intelligence Report</p>
            <h1 className="text-3xl font-bold text-white">Your AI Credit Score</h1>
            <p className="text-white/40 text-sm mt-1">
              Based on your financial behaviour assessment · Demo Model v0
            </p>
          </div>
          <div className="flex gap-3">
            <Link href="/assessment" className="btn-secondary text-sm py-2 gap-2">
              <RefreshCw size={14} />
              New Assessment
            </Link>
          </div>
        </div>

        {/* Demo banner */}
        <div className="mb-6 flex items-center gap-2.5 p-3 rounded-lg bg-amber-500/8 border border-amber-500/20">
          <AlertTriangle size={14} className="text-amber-400 shrink-0" />
          <p className="text-xs text-amber-300/80">
            <strong>Demo Mode:</strong> This score is generated by a mock rule-based model for demonstration purposes.
            Phase 2 will integrate a trained Random Forest model with SHAP explainability.
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-6">

          {/* ── Score Card (large) ────────────────────────── */}
          <div className="lg:col-span-1">
            <div className="card p-8 text-center h-full flex flex-col items-center justify-center gap-6">
              {/* Score ring */}
              <ScoreRing score={score} band={risk_band} />

              {/* Risk band badge */}
              <div className={cn('badge border', riskBg)}>
                <span className={cn('w-2 h-2 rounded-full', riskColor.replace('text-', 'bg-'))} />
                <span className={cn('font-semibold', riskColor)}>{riskLabel.toUpperCase()}</span>
              </div>

              {/* Confidence */}
              <div className="w-full">
                <div className="flex items-center justify-between text-xs mb-2">
                  <span className="text-white/40">Model Confidence</span>
                  <span className="text-white font-semibold">{Math.round(confidence * 100)}%</span>
                </div>
                <div className="h-1.5 rounded-full bg-white/[0.06] overflow-hidden">
                  <div
                    className="h-full rounded-full bg-blue-500"
                    style={{ width: `${Math.round(confidence * 100)}%` }}
                  />
                </div>
              </div>

              <div className="text-center pt-2 border-t border-white/[0.07] w-full">
                <p className="text-xs text-white/30">Model: Demo v0</p>
              </div>
            </div>
          </div>

          {/* ── Right column ─────────────────────────────── */}
          <div className="lg:col-span-2 flex flex-col gap-6">

            {/* Score interpretation */}
            <div className="card p-6">
              <div className="flex items-center gap-2 mb-5">
                <Brain size={16} className="text-blue-400" />
                <h2 className="font-semibold text-white text-sm">Score Interpretation</h2>
              </div>

              {/* Score bands visual */}
              <div className="space-y-3">
                {[
                  { label: 'Very High Risk', range: '0–29',  color: 'bg-red-500',     active: score < 30 },
                  { label: 'High Risk',      range: '30–49', color: 'bg-orange-500',  active: score >= 30 && score < 50 },
                  { label: 'Medium Risk',    range: '50–69', color: 'bg-amber-500',   active: score >= 50 && score < 70 },
                  { label: 'Low Risk',       range: '70–100',color: 'bg-emerald-500', active: score >= 70 },
                ].map(({ label, range, color, active }) => (
                  <div key={label} className={cn('flex items-center gap-3 p-2.5 rounded-lg transition-all', active && 'bg-white/[0.05]')}>
                    <div className={cn('w-2.5 h-2.5 rounded-full', color, active ? 'ring-2 ring-white/30' : 'opacity-40')} />
                    <span className={cn('text-sm flex-1', active ? 'text-white font-semibold' : 'text-white/35')}>
                      {label}
                    </span>
                    <span className={cn('text-xs font-mono', active ? 'text-white/60' : 'text-white/20')}>
                      {range}
                    </span>
                    {active && (
                      <span className="text-xs text-blue-300 font-semibold">← Your score</span>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Factors */}
            <div className="grid sm:grid-cols-2 gap-4">
              {/* Positive */}
              <div className="card p-6">
                <div className="flex items-center gap-2 mb-4">
                  <TrendingUp size={15} className="text-emerald-400" />
                  <h3 className="text-sm font-semibold text-white">Positive Factors</h3>
                </div>
                <div className="space-y-2.5">
                  {key_positive_factors.length > 0 ? (
                    key_positive_factors.map((f) => (
                      <div key={f} className="flex items-start gap-2.5">
                        <CheckCircle2 size={14} className="text-emerald-400 shrink-0 mt-0.5" />
                        <span className="text-sm text-white/70">{f}</span>
                      </div>
                    ))
                  ) : (
                    <p className="text-xs text-white/30 italic">No strong positive signals detected.</p>
                  )}
                </div>
              </div>

              {/* Negative */}
              <div className="card p-6">
                <div className="flex items-center gap-2 mb-4">
                  <AlertTriangle size={15} className="text-amber-400" />
                  <h3 className="text-sm font-semibold text-white">Areas to Improve</h3>
                </div>
                <div className="space-y-2.5">
                  {key_negative_factors.length > 0 ? (
                    key_negative_factors.map((f) => (
                      <div key={f} className="flex items-start gap-2.5">
                        <XCircle size={14} className="text-orange-400 shrink-0 mt-0.5" />
                        <span className="text-sm text-white/70">{f}</span>
                      </div>
                    ))
                  ) : (
                    <p className="text-xs text-white/30 italic">No major negative signals detected.</p>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ── Next Steps ──────────────────────────────────── */}
        <div className="mt-8 grid sm:grid-cols-3 gap-4">
          {[
            {
              icon: Brain,
              title: 'Why This Score?',
              desc: 'See feature-level explainability — which behaviours helped or hurt your score.',
              href: `/explainability?id=${id}`,
              cta: 'View Explanation',
            },
            {
              icon: Zap,
              title: 'Improve Your Score',
              desc: 'Use the what-if simulator to see how small changes can meaningfully improve your creditworthiness.',
              href: `/simulator?id=${id}`,
              cta: 'Open Simulator',
            },
            {
              icon: BarChart2,
              title: 'See Demo Profiles',
              desc: 'Explore how SCORIFY evaluates different financial profiles across risk bands.',
              href: '/demo',
              cta: 'View Demos',
            },
          ].map(({ icon: Icon, title, desc, href, cta }) => (
            <Link key={title} href={href} className="card-hover p-6 block group">
              <Icon size={20} className="text-blue-400 mb-3" />
              <h3 className="font-semibold text-white text-sm mb-2">{title}</h3>
              <p className="text-xs text-white/40 leading-relaxed mb-4">{desc}</p>
              <span className="inline-flex items-center gap-1 text-xs text-blue-400 font-medium group-hover:gap-2 transition-all">
                {cta} <ChevronRight size={12} />
              </span>
            </Link>
          ))}
        </div>

      </div>
    </div>
  )
}

export default function DashboardPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen pt-16 flex items-center justify-center">
        <Loader2 size={32} className="animate-spin text-blue-400" />
      </div>
    }>
      <DashboardContent />
    </Suspense>
  )
}
